#Specify Redis Server configuration here
redis:
  development:
    host: 159.8.128.94
    port: 5198
  test:
    host: 159.8.128.94
    port: 5198
  production:
    host: 159.8.128.94
    port: 5198

#Specify the Model to be used by Chatter, defaults to User
chatter:
  model: Provider
  key: qwerty97531